---
- name: Get general information from SonicWall TZ300
  hosts: localhost
  gather_facts: no
  vars:
    sonicwall_ip: "192.168.168.168"  # Replace with the actual SonicWall IP address
    sonicwall_user: "admin"       # Replace with SonicWall API username
    sonicwall_password: "password"  # Replace with SonicWall API password
    api_version: "v1"             # API version, default is usually v1

  tasks:
    - name: Authenticate to SonicWall and get token
      uri:
        url: "https://{{ sonicwall_ip }}/api/{{ api_version }}/auth"
        method: POST
        body_format: json
        body:
          username: "{{ sonicwall_user }}"
          password: "{{ sonicwall_password }}"
        headers:
          Content-Type: "application/json"
        validate_certs: no  # Disable SSL verification for self-signed certificates
        status_code: 200
        return_content: yes
      register: auth_response

    - name: Extract authentication token
      set_fact:
        auth_token: "{{ auth_response.json.token }}"

    - name: Get general system information
      uri:
        url: "https://{{ sonicwall_ip }}/api/{{ api_version }}/system/status"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ auth_token }}"
        validate_certs: no
        status_code: 200
        return_content: yes
      register: system_info

    - name: Display system information
      debug:
        msg: "{{ system_info.json }}"
