---
- name: Extract general info from SonicWall TZ300
  hosts: sonicwall
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ansible.builtin.ssh
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"  # Define your user as an environment variable
    ansible_password: "{{ lookup('env', 'ANSIBLE_PASS') }}"  # Define your password as an environment variable

  tasks:
    - name: Display system information (firmware, uptime, etc.)
      ansible.netcommon.cli_command:
        command: "show system-info"
      register: system_info_output

    - name: Print system information
      debug:
        msg: "{{ system_info_output.stdout_lines }}"

    - name: Display interface status
      ansible.netcommon.cli_command:
        command: "show interfaces status"
      register: interfaces_output

    - name: Print interfaces status
      debug:
        msg: "{{ interfaces_output.stdout_lines }}"

    - name: Display CPU and memory usage
      ansible.netcommon.cli_command:
        command: "show cpu-usage"
      register: cpu_usage_output

    - name: Print CPU and memory usage
      debug:
        msg: "{{ cpu_usage_output.stdout_lines }}"
