---
- name: Get SonicWall TZ300 settings
  hosts: localhost
  gather_facts: no

  vars:
    sonicwall_ip: "192.168.168.168"  # Replace with the SonicWall IP address
    sonicwall_username: "admin"   # Replace with your SonicWall API username
    sonicwall_password: "password"  # Replace with your SonicWall API password

  tasks:
    - name: Get SonicWall general system information
      uri:
        url: "https://{{ sonicwall_ip }}/api/sonicos/system"
        method: GET
        user: "{{ sonicwall_username }}"
        password: "{{ sonicwall_password }}"
        headers:
          Content-Type: "application/json"
        validate_certs: no  # Disable SSL verification, consider enabling it if using proper certificates
        return_content: yes
      register: sonicwall_response

    - name: Print the SonicWall response
      debug:
        var: sonicwall_response.content

    - name: Parse and display system settings
      set_fact:
        sonicwall_system_info: "{{ sonicwall_response.json }}"
      
    - name: Display system model and firmware version
      debug:
        msg: "Model: {{ sonicwall_system_info.system.system_model }}, Firmware Version: {{ sonicwall_system_info.system.firmware_version }}"
