---
- name: Sonicos API playbook for local SonicWall device
  hosts: localhost
  gather_facts: no
  vars:
    sonicwall_api_url: "https://{{ sonicwall_ip }}/api/sonicos/auth"
    sonicwall_ip: "192.168.1.1"  # Change this to the actual IP of the SonicWall
    api_username: "admin"         # Change to your SonicWall username
    api_password: "password"      # Change to your SonicWall password
    sonicos_api_response: {}
    sonicos_token: ""

  tasks:
    - name: Login to SonicWall API and retrieve token
      uri:
        url: "{{ sonicwall_api_url }}"
        method: POST
        body_format: json
        body:
          username: "{{ api_username }}"
          password: "{{ api_password }}"
        headers:
          Content-Type: "application/json"
        return_content: yes
        status_code: 200
        validate_certs: no  # Ignore SSL certificate validation for local devices
      register: login_response

    - name: Extract auth token from login response
      set_fact:
        sonicos_token: "{{ login_response.json.token }}"

    - name: Check if login was successful
      debug:
        msg: "Login successful, token: {{ sonicos_token }}"
      when: login_response.status == 200

    - name: Retrieve SonicWall API status
      uri:
        url: "https://{{ sonicwall_ip }}/api/sonicos/status"
        method: GET
        headers:
          Authorization: "Bearer {{ sonicos_token }}"
        return_content: yes
        validate_certs: no  # Ignore SSL certificate validation for local devices
      register: sonicos_api_response

    - name: Check if Sonicos API call was successful
      debug:
        msg: "API call was successful"
      when: sonicos_api_response.json.status.success == true

    - name: Display Sonicos API information details
      debug:
        msg: "{{ item }}"
      loop: "{{ sonicos_api_response.json.status.info }}"
